# Publiccode.yml test CircleCI config.yml 
version: 2
jobs:
  publiccode-test:
    docker:
      # specify the version
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: ls
      - run: go get -v github.com/italia/publiccode-parser-go/pcvalidate
      - run: /go/bin/pcvalidate publiccode.yml --remote-base-url https://raw.githubusercontent.com/{{ORG_NAME}}/{{REPO_NAME}}/master
