# Publiccode.yml test CircleCI config.yml 
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go get -v github.com/italia/publiccode-parser-go/pcvalidate
      - run: /go/bin/pcvalidate --remote-base-url https://raw.githubusercontent.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/master publiccode.yml
